<?php

declare(strict_types=1);

namespace App\Base\Presenters;

use Nette\Application\UI\Presenter;
use Nette\Bridges\ApplicationLatte\Template;

/**
 * @property Template $template
 */
abstract class BasePresenter extends Presenter
{

    public function startup(): void
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->setLayout(__DIR__ . '/../templates/@layout.latte');

        if ($this->isAjax()) {
            $this->redrawControl('flashes');
        }
    }
}
